const ACTION_BASE = "SATELLITES/";

export const ACTIONS = {
  UPDATE_SATELLITES: `${ACTION_BASE}UPDATE_SATELLITES`,
  SORT_BARRELS: `${ACTION_BASE}SORT_BARRELS`,
  SEARCH_BARRELS: `${ACTION_BASE}SEARCH_BARRELS`
};
